[27/Apr/2017 20:10:48] ERROR [django.request:256] Internal Server Error: /DynamfitRun
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/Develop/mdcs-v1.5_rc1/dynamfit/views.py", line 220, in runmodel
    }, context_instance=RequestContext(request))
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 208, in render_to_string
    t = self.get_template(template_name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 318, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 424, in compile_filter
    return FilterExpression(token, self)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 640, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ' not job_id_num == 'not found'' from 'if not job_id_num == 'not found''
[27/Apr/2017 20:12:26] ERROR [django.request:256] Internal Server Error: /DynamfitRun
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/Develop/mdcs-v1.5_rc1/dynamfit/views.py", line 221, in runmodel
    }, context_instance=RequestContext(request))
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 208, in render_to_string
    t = self.get_template(template_name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 318, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 424, in compile_filter
    return FilterExpression(token, self)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 640, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ' job_found' from 'if job_found'
[27/Apr/2017 20:13:01] ERROR [django.request:256] Internal Server Error: /DynamfitRun
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/Develop/mdcs-v1.5_rc1/dynamfit/views.py", line 221, in runmodel
    }, context_instance=RequestContext(request))
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/shortcuts.py", line 45, in render_to_response
    using=using)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader.py", line 115, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 208, in render_to_string
    t = self.get_template(template_name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
    nodelist = parser.parse()
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
    compiled_result = compile_func(self, token)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 318, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 424, in compile_filter
    return FilterExpression(token, self)
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/template/base.py", line 640, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '% if job_found %' from '% if job_found %'
[27/Apr/2017 20:16:06] WARNING [django.request:170] Not Found: /Dynamfit
[27/Apr/2017 21:41:15] ERROR [django.request:256] Internal Server Error: /descchar_view
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/Develop/mdcs-v1.5_rc1/descchar/views.py", line 132, in check
    if int( tp.split(',')[-1] ) == int(count):
ValueError: invalid literal for int() with base 10: ''
[27/Apr/2017 21:41:51] ERROR [django.request:256] Internal Server Error: /DynamfitRun
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/Develop/mdcs-v1.5_rc1/dynamfit/views.py", line 193, in runmodel
    if int( tp.split(',')[-2] ) == int(count):
ValueError: invalid literal for int() with base 10: ''
[27/Apr/2017 21:42:42] ERROR [django.request:256] Internal Server Error: /DynamfitRun
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/Develop/mdcs-v1.5_rc1/dynamfit/views.py", line 193, in runmodel
    if int( tp.split(',')[-2] ) == int(count):
ValueError: invalid literal for int() with base 10: ''
[27/Apr/2017 21:43:18] ERROR [django.request:256] Internal Server Error: /DynamfitRun
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/Develop/mdcs-v1.5_rc1/dynamfit/views.py", line 193, in runmodel
    if int( tp.split(',')[-2] ) == int(count):
ValueError: invalid literal for int() with base 10: ''
[27/Apr/2017 21:46:06] ERROR [django.request:256] Internal Server Error: /DynamfitRun
Traceback (most recent call last):
  File "/home/NANOMINE/anaconda2/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/NANOMINE/Develop/mdcs-v1.5_rc1/dynamfit/views.py", line 193, in runmodel
    count = 0
ValueError: invalid literal for int() with base 10: ''
